# ----------------------------------------------------------------
# Universal Import
# ----------------------------------------------------------------
from google.adk.agents import LlmAgent, LoopAgent, SequentialAgent

# ------------------------------------------
# Prompt Loop Imports
# ------------------------------------------
from tools.save_prompt import save_prompt
from tools.read_prompt import read_prompt
from tools.exit_prompt_loop import exit_prompt_loop

# ---------------------------------------
# Planner Import
# ---------------------------------------
from tools.access_plan import create_plan
from tools.get_prompt import get_prompt

# ---------------------------------------------
# Code Loop Imports
# ---------------------------------------------
from tools.access_plan import read_plan
from tools.read_code import read_code
from tools.save_code import save_code
from tools.list_code_files import list_code_files
from tools.exit_code_loop import exit_code_loop
from tools.create_folder import create_folder


model = "openai/gpt-4.1"
COMPLETION_PHRASE = "PASS"

prompt_generator_agent = LlmAgent(
    name="PromptGeneratorAgent",
    model=model,
    description="Use this agent to generate the prompt for the project. Give it information such as programming language, framework or any other specifics. If the user doesnt provide, ask for it to build the best possible prompt.",
    instruction="""
You are a masterful prompt generator agent.
You will be provided with a programming language, framework and other specific information
Use said information to generate a beautiful prompt engineered prompt
After generating, use the save_prompt tool to save it for the critic to review
""",
    tools=[save_prompt]
)

prompt_critic_agent = LlmAgent(
    name="PromptCriticAgent",
    model=model,
    include_contents="none",
    instruction=f"""
You are a Constructive Critic AI agent, reviewing a prompt.
Use the read_prompt tool to get access to the prompt.
Criteria:
- It will generate the best code as possible
- It is clear and easy to understand
- It will work

# Task
Check the prompt against the above criteria
If you feel the criteria is not met, say FAIL, and provide feedback.
If you feel the criteria is met, respond only with {COMPLETION_PHRASE} and nothing else 
""",
    description="Reviews the prompt draft to see if its good.",
    tools=[read_prompt]
)

prompt_refiner_agent = LlmAgent(
    name="PromptRefinerAgent",
    model=model,
    instruction=f"""
You are a prompt refiner refining a document based on feedback or exiting the process
Use the read_prompt tool to get access to the prompt.
Analyze the response of the prompt_critic_agent
If the prompt_critic_agent's response is {COMPLETION_PHRASE}, use the exit_loop function. DO NOT DO ANYTHING ELSE
Otherwise:
- Apply the suggestions to the prompt file with the save_prompt tool 
""",
description="Refines prompt or exits the loop",
tools=[save_prompt, read_prompt, exit_prompt_loop]
)

prompt_refinement_loop = LoopAgent(
    name="PromptRefinmentLoop",
    sub_agents=[
        prompt_critic_agent,
        prompt_refiner_agent
    ],
    max_iterations=5
)

planner_agent = LlmAgent(
    name="PlannerAgent",
    model=model,
    description="Plans steps on how to code the project",
    instruction=f"""
You are a planner agent.
Plan specifically:
- What files should be made
- What each file should do
- Ensure synchronisation between files (files are compatible with each other)
- In MD format

Using the prompt file. To get access to the prompt, use the get_prompt tool
USE THE create_plan TOOL TO CREATE THE PLAN. THE REST OF THE FLOW WONT WORK IF THE PLAN ISNT SAVED!!!
""",
    tools=[create_plan, get_prompt]
)

coder_agent = LlmAgent(
    name="CoderAgent",
    model=model,
    description="Use this agent to generate code to complete the required project",
    instruction="""
You are a master code developer.
Use the read_plan tool to read the plan generated by your boss, the planner
Create a project folder using the create_folder tool
Generate code in the project folder to it
Then, use the save_code tool to save the code.
""",
    tools=[read_plan, save_code, create_folder]
)

code_critic_agent = LlmAgent(
    name="CodeCriticAgent",
    model=model,
    include_contents="none",
    instruction=f"""
You are a Code Critic AI agent, reviewing the code generated by the coder.
Use the list_code_files tool to see which code files it actually made.
Then use the read_code tool and supply the file name to get the contents.
Do this for all code files

Criteria:
- The code is actually for the project and not for something random
- The code is efficient
- The code is production-ready
- It will work

# Task
Check the project files against the above criteria
If you feel the criteria is not met, say FAIL, and provide feedback.
If you feel the criteria is met, respond only with {COMPLETION_PHRASE} and nothing else 
""",
    description="Reviews the code to see if its good.",
    tools=[list_code_files, read_code]
)

code_refiner_agent = LlmAgent(
    name="CodeRefinerAgent",
    model=model,
    instruction=f"""
You are a code refiner refining the code files based on feedback or exiting the process
Use the list_code_files tool to see what files actually exist.
Then use the read_code tool to get the contents of the file
Analyze the response of the code_critic_agent
If the code_critic_agent's response is {COMPLETION_PHRASE}, use the exit_loop function. DO NOT DO ANYTHING ELSE
Otherwise:
- Apply the suggestions to the corresponding code files with the save_code tool 
""",
description="Refines prompt or exits the loop",
tools=[list_code_files, read_code, save_code, exit_code_loop]
)

code_refinement_loop = LoopAgent(
    name="CodeRefinmentLoop",
    sub_agents=[
        code_critic_agent,
        code_refiner_agent
    ],
    max_iterations=5
)

congratulator_agent = LlmAgent(
    name="CongratulatorAgent",
    model=model,
    description="Gives a congrats message for finishing",
    instruction="Just generate a few sentences saying you are done and are the tests have passed. Also, thank the user for using this tool and be enthusiastic about it."
)

root_agent = SequentialAgent(
    name="DevTeamPipeline",
    sub_agents=[
        prompt_generator_agent,
        prompt_refinement_loop,
        planner_agent,
        coder_agent,
        code_refinement_loop,
        congratulator_agent
    ],
    description="""
- Uses the prompt generator to generate a prompt
- Then the prompt refinement loop to refine it
- Then uses the coder agent to code it
- Then the code refinement loop to refine it
- Then use the congratulator agent to give the finishing touches.
""",
) 